window.catalyst_objects = {
	groups : [ 
		{ id: 0000, title: 'ProdOps' }, 
		{ id: 0001, title: 'HR' }, 
		{ id: 0002, title: 'Corp Strategy' }, 
		{ id: 0003, title: 'Finance/IT/WPR' }, 
		{ id: 0004, title: 'Legal' }, 
		{ id: 0005, title: 'Go-To-Market' }, 
		{ id: 0006, title: 'Marketing' }, 
		{ id: 0007, title: 'FieldOps' }, 
		{ id: 0008, title: 'CSOps' }, 
		{ id: 0009, title: 'GTMOps' }
	],
	regions : [
		{ id: 000, title: 'Sunnyvale', location : { lat: 37.368830, lng: -122.036350}, employees: 3783, region: 'AMERICAS' }, 
		{ id: 001, title: 'Bangalore', location : { lat: 12.971599, lng: 77.594563}, employees: 2165, region: 'INDIA' },
		{ id: 002, title: 'RTP', location : { lat: 35.899168, lng: -78.863640}, employees: 1939, region: 'AMERICAS' }, 
		{ id: 003, title: 'Winchita, KS', location : { lat: 37.688889, lng: -97.336111}, employees: 737, region: 'AMERICAS' },
		{ id: 004, title: 'Vienna, VA', location : { lat: 38.901223, lng: -77.265260}, employees: 337, region: 'AMERICAS' }, 
		{ id: 005, title: 'Schiphol Rijk', location : { lat: 0, lng: 0}, employees: 331, region: 'EMEA' },
		{ id: 006, title: 'Waltham, MA', location : { lat: 0, lng: 0}, employees: 281, region: '' },
		{ id: 007, title: 'Pittsburgh, PA', location : { lat: 0, lng: 0}, employees: 257, region: '' }, 
		{ id: 008, title: 'Munich', location : { lat: 0, lng: 0}, employees: 256, region: '' },
		{ id: 009, title: 'Rivermead', location : { lat: 0, lng: 0}, employees: 255, region: '' }, 
		{ id: 010, title: 'Tokyo', location : { lat: 0, lng: 0}, employees: 230, region: '' },
		{ id: 011, title: 'Boulder, CO', location : { lat: 0, lng: 0}, employees: 176, region: '' }, 
		{ id: 012, title: 'Singapore', location : { lat: 0, lng: 0}, employees: 167, region: '' },
		{ id: 013, title: 'Paris', location : { lat: 0, lng: 0}, employees: 146, region: '' },
		{ id: 014, title: 'New York City, NY', location : { lat: 0, lng: 0}, employees: 142, region: '' },
		{ id: 015, title: 'Dallas, TX', location : { lat: 0, lng: 0}, employees: 108, region: '' }, 
		{ id: 016, title: 'Beijing', location : { lat: 0, lng: 0}, employees: 93, region: '' },
		{ id: 017, title: 'Sydney', location : { lat: 0, lng: 0}, employees: 84, region: '' },
		{ id: 018, title: 'Dusseldorf', location : { lat: 0, lng: 0}, employees: 79, region: '' },
		{ id: 019, title: 'Bellevue, WA', location : { lat: 0, lng: 0}, employees: 75, region: '' }, 
		{ id: 020, title: 'Greenwood Village, CO', location : { lat: 0, lng: 0}, employees: 72, region: '' },
		{ id: 021, title: 'Melbourne', location : { lat: 0, lng: 0}, employees: 71, region: '' },
		{ id: 022, title: 'Neuisenburg', location : { lat: 0, lng: 0}, employees: 70, region: '' },
		{ id: 023, title: 'Dalian', location : { lat: 0, lng: 0}, employees: 69, region: '' }, 
		{ id: 024, title: 'Vancouver, BC', location : { lat: 0, lng: 0}, employees: 68 },
		{ id: 025, title: 'Edison, NJ', location : { lat: 0, lng: 0}, employees: 60 }, 
		{ id: 026, title: 'Mississauga', location : { lat: 0, lng: 0}, employees: 58 },
		{ id: 027, title: 'Stuttgart', location : { lat: 0, lng: 0}, employees: 57 }, 
		{ id: 028, title: 'Zurich', location : { lat: 0, lng: 0}, employees: 57 },
		{ id: 029, title: 'Hong Kong', location : { lat: 0, lng: 0}, employees: 55 },
		{ id: 030, title: 'Petach Tikva', location : { lat: 0, lng: 0}, employees: 54 },
		{ id: 031, title: 'Shanghai', location : { lat: 0, lng: 0}, employees: 53 }, 
		{ id: 032, title: 'Milan', location : { lat: 0, lng: 0}, employees: 53 },
		{ id: 033, title: 'Schaumburg, IL', location : { lat: 0, lng: 0}, employees: 52 }, 
		{ id: 034, title: 'Austin, TX', location : { lat: 0, lng: 0}, employees: 51 },
		{ id: 035, title: 'Taipei City', location : { lat: 0, lng: 0}, employees: 51 }, 
		{ id: 036, title: 'Atlanta, GA', location : { lat: 0, lng: 0}, employees: 49 },
		{ id: 037, title: 'Scottsdale, AZ', location : { lat: 0, lng: 0}, employees: 46 },
		{ id: 038, title: 'Edina, MN', location : { lat: 0, lng: 0}, employees: 45 },
		{ id: 039, title: 'Seoul', location : { lat: 0, lng: 0}, employees: 45 }, 
		{ id: 040, title: 'Hamburg', location : { lat: 0, lng: 0}, employees: 44 },
		{ id: 041, title: 'London', location : { lat: 0, lng: 0}, employees: 43 }, 
		{ id: 042, title: 'Madrid', location : { lat: 0, lng: 0}, employees: 43 },
		{ id: 043, title: 'Houston, TX', location : { lat: 0, lng: 0}, employees: 42 }, 
		{ id: 044, title: 'Conventry', location : { lat: 0, lng: 0}, employees: 42 },
		{ id: 045, title: 'Vienna', location : { lat: 0, lng: 0}, employees: 42 },
		{ id: 046, title: 'Austin, TX', location : { lat: 0, lng: 0}, employees: 41 },
		{ id: 047, title: 'Irvine, CA', location : { lat: 0, lng: 0}, employees: 35 }, 
		{ id: 048, title: 'Southfield, MI', location : { lat: 0, lng: 0}, employees: 35 },
		{ id: 049, title: 'Wayne, PA', location : { lat: 0, lng: 0}, employees: 35 }, 
		{ id: 050, title: 'Sherman Oaks, CA', location : { lat: 0, lng: 0}, employees: 34 },
		{ id: 051, title: 'Kista', location : { lat: 0, lng: 0}, employees: 33 }, 
		{ id: 052, title: 'Diegem', location : { lat: 0, lng: 0}, employees: 31 },
		{ id: 053, title: 'Cheadle', location : { lat: 0, lng: 0}, employees: 30 },
		{ id: 054, title: 'San Diego, CA', location : { lat: 0, lng: 0}, employees: 29 },
		{ id: 055, title: 'Moscow', location : { lat: 0, lng: 0}, employees: 28 }, 
		{ id: 056, title: 'New Delhi', location : { lat: 0, lng: 0}, employees: 27 },
		{ id: 057, title: 'El Segundo', location : { lat: 0, lng: 0}, employees: 25 }, 
		{ id: 058, title: 'Tel Aviv', location : { lat: 0, lng: 0}, employees: 25 },
		{ id: 059, title: 'Charlotte, NC', location : { lat: 0, lng: 0}, employees: 24 },
		{ id: 060, title: 'Sao Paulo', location : { lat: 0, lng: 0}, employees: 23 },
		{ id: 061, title: 'Dubai', location : { lat: 0, lng: 0}, employees: 22 },
		{ id: 062, title: 'Mumbai', location : { lat: 0, lng: 0}, employees: 21 },
		{ id: 063, title: 'Creve Coeur, MO', location : { lat: 0, lng: 0}, employees: 19 }, 
		{ id: 064, title: 'Lake Oswego, OR', location : { lat: 0, lng: 0}, employees: 19 },
		{ id: 065, title: 'Dublin, OH', location : { lat: 0, lng: 0}, employees: 17 }, 
		{ id: 066, title: 'Osaka', location : { lat: 0, lng: 0}, employees: 17 },
		{ id: 067, title: 'Copenhagen', location : { lat: 0, lng: 0}, employees: 17 }, 
		{ id: 068, title: 'Miami, FL', location : { lat: 0, lng: 0}, employees: 16 },
		{ id: 069, title: 'Brisbane', location : { lat: 0, lng: 0}, employees: 16 },
		{ id: 070, title: 'Walldorf', location : { lat: 0, lng: 0}, employees: 16 },
		{ id: 071, title: 'Mexico City', location : { lat: 0, lng: 0}, employees: 15 },
		{ id: 072, title: 'Johannesburg', location : { lat: 0, lng: 0}, employees: 15 },
		{ id: 073, title: 'Shenzhen', location : { lat: 0, lng: 0}, employees: 14 }, 
		{ id: 074, title: 'Chicago, IL', location : { lat: 0, lng: 0}, employees: 13 },
		{ id: 075, title: 'Canberra', location : { lat: 0, lng: 0}, employees: 13 }, 
		{ id: 076, title: 'Guangzhou', location : { lat: 0, lng: 0}, employees: 13 },
		{ id: 077, title: 'Jakarta', location : { lat: 0, lng: 0}, employees: 13 }, 
		{ id: 078, title: 'Santiago', location : { lat: 0, lng: 0}, employees: 12 },
		{ id: 079, title: 'Kuala Lumpur', location : { lat: 0, lng: 0}, employees: 12 },
		{ id: 080, title: 'Chengdu', location : { lat: 0, lng: 0}, employees: 11 },
		{ id: 081, title: 'Berlin', location : { lat: 0, lng: 0}, employees: 11 },
		{ id: 082, title: 'Espoo', location : { lat: 0, lng: 0}, employees: 11 },
		{ id: 083, title: 'Warsaw', location : { lat: 0, lng: 0}, employees: 11 }, 
		{ id: 084, title: 'Brookfield, WI', location : { lat: 0, lng: 0}, employees: 10 },
		{ id: 085, title: 'Salt Lake City, UT', location : { lat: 0, lng: 0}, employees: 10 }, 
		{ id: 086, title: 'Bangkok', location : { lat: 0, lng: 0}, employees: 10 },
		{ id: 087, title: 'Cincinnati, OH', location : { lat: 0, lng: 0}, employees: 9 }, 
		{ id: 088, title: 'Hillsboro, OR', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 089, title: 'Rochester, NY', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 090, title: 'Nagoya', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 091, title: 'Lagos', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 092, title: 'Lausanne', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 093, title: 'Nurnberg', location : { lat: 0, lng: 0}, employees: 9 }, 
		{ id: 094, title: 'Rome', location : { lat: 0, lng: 0}, employees: 9 },
		{ id: 095, title: 'Bentonville, AR', location : { lat: 0, lng: 0}, employees: 8 }, 
		{ id: 096, title: 'Indianapolis, IN', location : { lat: 0, lng: 0}, employees: 8 },
		{ id: 097, title: 'Bern', location : { lat: 0, lng: 0}, employees: 8 }, 
		{ id: 098, title: 'Toulouse', location : { lat: 0, lng: 0}, employees: 8 },
		{ id: 099, title: 'Buenos Aires', location : { lat: 0, lng: 0}, employees: 7 },
		{ id: 100, title: 'Barcelona', location : { lat: 0, lng: 0}, employees: 7 },
		{ id: 101, title: 'Istanbul', location : { lat: 0, lng: 0}, employees: 7 },
		{ id: 102, title: 'Lyon', location : { lat: 0, lng: 0}, employees: 7 },
		{ id: 103, title: 'Oslo', location : { lat: 0, lng: 0}, employees: 7 }, 
		{ id: 104, title: 'Ft. Collins, CO', location : { lat: 0, lng: 0}, employees: 6 },
		{ id: 105, title: 'Independence, OH', location : { lat: 0, lng: 0}, employees: 6 }, 
		{ id: 106, title: 'Perth', location : { lat: 0, lng: 0}, employees: 6 },
		{ id: 107, title: 'Edinburgh', location : { lat: 0, lng: 0}, employees: 6 }, 
		{ id: 108, title: 'Riyadh', location : { lat: 0, lng: 0}, employees: 6 },
		{ id: 109, title: 'Des Moines, IA', location : { lat: 0, lng: 0}, employees: 5 },
		{ id: 110, title: 'Overland Park, KS', location : { lat: 0, lng: 0}, employees: 5 },
		{ id: 111, title: 'Seattle, WA', location : { lat: 0, lng: 0}, employees: 5 },
		{ id: 112, title: 'Penang', location : { lat: 0, lng: 0}, employees: 5 },
		{ id: 113, title: 'Nashville, TN', location : { lat: 0, lng: 0}, employees: 4 },
		{ id: 114, title: 'Hangzhou', location : { lat: 0, lng: 0}, employees: 4 },
		{ id: 115, title: 'Wuhan', location : { lat: 0, lng: 0}, employees: 4 }, 
		{ id: 116, title: 'Almaty', location : { lat: 0, lng: 0}, employees: 4 },
		{ id: 117, title: 'Prague', location : { lat: 0, lng: 0}, employees: 4 }, 
		{ id: 118, title: 'Las Vegas, NV', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 119, title: 'Auckland', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 120, title: 'Gothenburg', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 121, title: 'Luxembourg', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 122, title: 'Chennai', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 123, title: 'Hyderabad', location : { lat: 0, lng: 0}, employees: 3 }, 
		{ id: 124, title: 'Pune', location : { lat: 0, lng: 0}, employees: 3 },
		{ id: 125, title: 'Omaha, NE', location : { lat: 0, lng: 0}, employees: 2 }, 
		{ id: 126, title: 'Tucson, AZ', location : { lat: 0, lng: 0}, employees: 2 },
		{ id: 127, title: 'Fukuoka', location : { lat: 0, lng: 0}, employees: 2 }, 
		{ id: 128, title: 'Nanjing', location : { lat: 0, lng: 0}, employees: 2 },
		{ id: 129, title: 'Wellington', location : { lat: 0, lng: 0}, employees: 2 },
		{ id: 130, title: 'Rio De Janiero', location : { lat: 0, lng: 0}, employees: 1 },
		{ id: 131, title: 'Adelaide', location : { lat: 0, lng: 0}, employees: 1 },
		{ id: 132, title: 'Stavanger', location : { lat: 0, lng: 0}, employees: 1 },
		{ id: 133, title: 'Kolkata', location : { lat: 0, lng: 0}, employees: 1 }, 
	],
	card_types : [
		{ id: 0000, title: 'Candor', img_url: "images/candor-card.png" }, 
		{ id: 0001, title: 'Clarity', img_url: "images/clarity-card.png" }, 
		{ id: 0002, title: 'Ownership', img_url: "images/ownership-card.png" }, 
		{ id: 0003, title: 'Speed', img_url: "images/speed-card.png" }
	],
}